name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: |
          set -e
          terraform apply -auto-approve || {
          echo "Terraform apply failed. Running destroy..."
          terraform destroy -auto-approve
          exit 1
          } 
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Public IP from Terraform
        run: |
          public_ip=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$public_ip" >> ${GITHUB_ENV}
        shell: /usr/bin/bash -e {0}
        
      - name: Update Ansible Inventory
        run: |
          echo "[web]" > ansible/inventory
          echo "$PUBLIC_IP ansible_user=ubuntu >> ansible/inventory

  cleanup:
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ failure() }}
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
        working-directory: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
